### PR TITLE
Add "max" payment field value to payment_v2

### PR DESCRIPTION
**Pull request by jeffgrunewald**
Satisfies the proto change requirement for https://github.com/helium/blockchain-core/pull/1138 as outlined in https://github.com/helium/blockchain-core/issues/1060.

### CODE REVIEW

**Comment by madninja** [comment]
let's make sure that @allenan is ok with the yarn dep bumps there

**Comment by jeffgrunewald** [comment]
> let's make sure that @allenan is ok with the yarn dep bumps there

Not married to them if he isn’t; just trying to make the dependabot warnings go away

**Comment by jeffgrunewald** [comment]
@madninja fyi i removed the changes to yarn package versions to clean up this PR and make it ready to merge in preparation of finalizing the main change in blockchain-core.

**Comment by madninja** [comment]
> @madninja fyi i removed the changes to yarn package versions to clean up this PR and make it ready to merge in preparation of finalizing the main change in blockchain-core.

is @allenan ok with this change?

**Comment by jeffgrunewald** [comment]
> is @allenan ok with this change?

with the additional proto field? i just completely removed the last change you wanted to check with @allenan about

**Comment by madninja** [comment]
> > is @allenan ok with this change?
> 
> with the additional proto field? i just completely removed the last change you wanted to check with @allenan about

Ah! the yarn changes were what you removed.. I see it now..

**Pull request merged**
