### PR TITLE
Add rx1/2 window to helium packet

### PR DESCRIPTION
**Pull request by macpie**

### CODE REVIEW

**Comment by madninja** [comment]
This can’t be right since it renumbers fields pretty drastically?

**Comment by vihu** [comment]
@macpie Yeah, you can't change the proto like that without breaking backward compat. Instead just add `rx1_window` and `rx2_window` extra fields.

**Comment by macpie** [comment]
This should be ok as it is only used for communication . Had a talk with @Vagabond about it

**Comment by vihu** [comment]
> This should be ok as it is only used for communication . Had a talk with @Vagabond about it

Hmm, I guess that's fair, that packet(s) themselves never really show up in the ledger or any txn, so presumably it should be fine?

**Comment by madninja** [comment]
That is fair.. but it would stop gateways that are not using the latest photo from being able to deliver packets right?

**Comment by macpie** [comment]
Yes indeed this would need to be a coordinated update with router

**Comment by macpie** [comment]
This is not to be merged until I got the rest done anyway (wanted to make this a draft but forgot).

**Comment by Vagabond** [comment]
I would strongly recommend against renumbering fields in any case, it's not worth the extra explosion risk.

**Review by Vagabond — APPROVED** [review]

**Pull request merged**
