### PR TITLE
Remove rustfmt in tonic-build dependency by default to allow production builds without rustfmt

### PR DESCRIPTION
**Pull request by mullerch**
Actually, by default, rustfmt is needed for all builds. As rustfmt is here only to prettify the generated proto files (very useful for debug), it can be removed for production builds.

I could not find a way to differentiate the build-dependency depending on the profile (dev, release).

### CODE REVIEW

**Comment by mullerch** [comment]
What about now?

**Comment by madninja** [comment]
> What about now?

nice, does that work for you?

**Comment by mullerch** [comment]
Yes that works fine. Looks like unused functions do not imply a dependency.

**Comment by madninja** [comment]
> Yes that works fine. Looks like unused functions do not imply a dependency.

Yeah I believe it's literally shelling out to rustfmt if format is set to true

**Comment by madninja** [comment]
Thanks @mullerch !

**Pull request merged**
